name: mis_lab3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  firebase_auth: ^4.0.0
  awesome_notifications: ^0.9.2
  syncfusion_flutter_calendar: ^24.2.3
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
